### ISSUE TITLE
Broken knowledge base article link

### ISSUE THREAD

**Issue by Q-lds** [ProtonVPN/linux-cli#11] opened 2021-06-23 05:07 UTC
The[ knowledge base article](https://github.com/ProtonVPN/linux-cli/blob/master/to-add) in the readme is currently broken as it returns a 404 error.

And so is the link to the instructions on how to update ProtonVPN-CLI

```
A new Update for ProtonVPN-CLI (v2.2.7) is available.
Follow the Update instructions on
https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#updating-protonvpn-cli
```

**Comment by calexandru2018** [comment] 2021-06-23 07:41
Hey @Q-lds 

This is actually a duplicate of #5 thus I'll be closing this one.

**Closed by calexandru2018** 2021-06-23 07:41 UTC
