### ISSUE TITLE
Unable to use CLI and CUI after upgrading to the official version. (3.7.2)

### ISSUE THREAD

**Issue by BenD780x9** [ProtonVPN/linux-cli#30] opened 2021-07-08 08:00 UTC
Hey, I was using the old version of the CLI (2.2.4) and it works fine.

` protonvpn-cli c   
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==3.7.2', 'console_scripts', 'protonvpn-cli')())
  File "/usr/bin/protonvpn-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

`

**Comment by calexandru2018** [comment] 2021-07-08 08:06
Duplicate of #20

**Closed** 2021-07-08 08:06 UTC
