### ISSUE TITLE
[BUG]  Protonvpn newest update doesn't work

### ISSUE THREAD

**Issue by kmakeel** [ProtonVPN/linux-cli#186] opened 2020-06-04 13:13 UTC
**Describe the bug**
Protonvpn was running without any problems but when I updated to the latest version v2.2.4  doesn't work anymore

**To Reproduce**

**Expected behavior**

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn-gui", line 6, in <module>
    from protonvpn_linux_gui.gui import initialize_gui
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_linux_gui/gui.py", line 16, in <module>
    from .utils import (
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_linux_gui/utils.py", line 12, in <module>
    from protonvpn_cli.utils import (
ImportError: cannot import name 'make_ovpn_template' from 'protonvpn_cli.utils' (/usr/local/lib/python3.7/dist-packages/protonvpn_cli/utils.py)

**Desktop (please complete the following information):**
 - OS: [Debian 10]
 - Python Version: [3.7]
 - ProtonVPN-CLI Version: [v2.2.4]

**Additional context**

**Comment by calexandru2018** [comment] 2020-06-04 13:20
Hello @kmakeel 

The issue that you are posting is regarding the GUI (`/usr/local/bin/protonvpn-gui`) and not the CLI.

This has already been reported previously, you will need to wait until a new PyPi update is released or just clone the linux-gui repo.

Closing this issue since this is a duplicate of [#72](https://github.com/ProtonVPN/linux-gui/issues/72)

**Closed by calexandru2018** 2020-06-04 13:20 UTC
